AWSTemplateFormatVersion: '2010-09-09'
Parameters:
    DynamoName:
        Type: String
    DynamoKey:
        Type: String
      
Resources:
  DynamoCloud:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: !Ref DynamoKey
        AttributeType: S
      KeySchema:
      - AttributeName: !Ref DynamoKey
        KeyType: HASH
      SSESpecification:
        SSEEnabled: true
Outputs:
  DynamoCloud:
      Value: !Ref DynamoCloud
      Export:
        Name: DynamoCloud
  DynamoCloudArn:
      Value: !GetAtt DynamoCloud.Arn
      Export:
        Name: DynamoCloudArn
